version: '2'
services:
    overwatch-app:
        image: overwatch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://overwatch-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=overwatch-elasticsearch:9300
        ports:
            - 8080:8080
    overwatch-mssql:
        extends:
            file: mssql.yml
            service: overwatch-mssql
    overwatch-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: overwatch-elasticsearch
